### PR TITLE
Update plugins

### LINKED ISSUE #102: use setup-java@v3
* change seems to be driven by https://github.com/actions/setup-java/pull/290
* other actions like checkout and cache have similar v3 releases

### PR DESCRIPTION
**Pull request by andreisilviudragnea**
- Updated `actions/cache` from `v2` to `v3`
- Updated `actions/checkout` from `v2` to `v3`
- Updated `actions/setup-java` from `v2` to `v3`

Fixes #102

### CODE REVIEW

**Comment by andreisilviudragnea** [comment]
@yanns

**Review by yanns — APPROVED** [review]

**Comment by andreisilviudragnea** [comment]
@djspiewak

**Comment by andreisilviudragnea** [comment]
@RustedBones @kubukoz

**Comment by pjfanning** [comment]
@andreisilviudragnea thanks for doing the PR - I don't have merge rights so can't help on that front.

I just raised #104 as I was told about this feature today. Just highlighting this just in case it is of interest.

**Review by kubukoz — APPROVED** [review]

**Comment by andreisilviudragnea** [comment]
Who has merge rights and can help me with an approve?

**Comment by rossabaker** [comment]
As far as I know, only @djspiewak.

Incidentally, the functionality of this plugin is also present in sbt-typelevel.  Not to discourage work here, but that is a bit wider community effort.

**Comment by armanbilge** [comment]
sbt-typelevel-github-actions made this updates in https://github.com/typelevel/sbt-typelevel/pull/234 and are available in 0.5.x milestones

**Pull request closed without merging**
